# Sistema de Análisis del Mercado de Automoción

### Crisitian Cabrera Pinto y Álex Rafael de la Cruz Sánchez

Trabajo SBD y SAA

In [1]:
#Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Lectura de ficheros
df_vehiculos = pd.read_csv('vehiculos.json')
df_ventas_mantenimiento = pd.read_csv('ventas_mantenimiento.csv')
df_opiniones = pd.read_csv('opiniones_clientes.xml')

In [3]:
df_vehiculos.head()

,vehiculo_id,marca,modelo,anio_fabricacion,combustible,transmision,potencia_cv,cilindrada,consumo_urbano,consumo_extraurbano,emisiones_co2,precio_base,segmento
0,VH001,Peugeot,208,2018,Híbrido,Manual,147,1400,6.9,5.5,149,34600,Compacto
1,VH002,Hyundai,i20,2018,Gasolina,Manual,219,2000,4.1,4.1,149,36500,Sedán
2,VH003,Kia,Ev6,2020,Híbrido,Manual,130,2200,5.7,4.3,107,34800,Deportivo
3,VH004,Ford,Puma,2018,Gasolina,Automática,178,2000,5.1,3.6,138,35200,SUV
4,VH005,Hyundai,i20,2022,Gasolina,Automática,237,1400,6.8,3.6,109,38800,SUV

In [4]:
df_ventas_mantenimiento.head()

,venta_id,vehiculo_id,fecha_venta,region_vendedor,precio_venta_real,kilometraje_venta,servicios_realizados,coste_mantenimiento_anual,incidencias_mecanicas,valor_residual_estimado
0,VT001,VH001,2023-03-01,Cataluña,34536,168,0,992,0,12937
1,VT002,VH001,2023-01-24,País Vasco,31929,9835,1,992,0,6894
2,VT003,VH001,2023-10-11,País Vasco,30964,16270,3,992,0,10366
3,VT004,VH002,2023-10-20,Andalucía,31897,44127,0,1030,0,6739
4,VT005,VH003,2023-08-27,Andalucía,34964,20361,2,896,3,18098

In [5]:
df_opiniones.head()

,review_id,vehiculo_id,cliente_id,puntuacion_conjunta,confort,seguridad,eficiencia,diseno,fiabilidad,recomendacion,texto_review
0,RV001,VH204,CUST173,3.4,3.4,3.9,4.8,3.6,3.0,No,"Problemático, poco espacio"
1,RV002,VH249,CUST034,3.0,3.1,3.4,4.1,2.9,2.6,No,"Decepcionante, poco espacio"
2,RV003,VH244,CUST038,5.0,5.0,5.0,5.0,5.0,5.0,Si,"Eficiente vehículo, gran rendimiento"
3,RV004,VH280,CUST022,3.9,3.9,3.9,4.8,3.5,3.1,Si,"Problemático, precio elevado"
4,RV005,VH125,CUST153,4.0,4.2,4.5,4.2,4.1,5.0,Si,"Lento, precio elevado"

### Fase 0: Datos

### Fase 1: Selección y comprensión del dominio

### Fase 2: Preprocesamiento y limpieza

### Fase 3: Minería de Datos (KDD)